### ISSUE TITLE
Game crashed upon running /reload

### ISSUE THREAD

**Issue by Neko2n** [Witixin1512/ArmorSetEffects#5]
Not exactly sure how this happened as my /reload command was working just fine one minute, and then the next minute my screen went gray and the game froze. This eventually led to a crash with this log output:

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.witixin.seteffect.handler.PlayerHandler.onEntityTick(PlayerHandler.java:34)
	at net.minecraftforge.eventbus.ASMEventHandler_2761_PlayerHandler_onEntityTick_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[19Nov2021 01:37:11.820] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 2c986657-7041-4b88-a043-b1b6d118a67f
[19Nov2021 01:37:11.825] [Render thread/INFO] [mezz.jei.util.LoggedTimer/]: Starting JEI...
[19Nov2021 01:37:11.824] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_281]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_281]
	at net.witixin.seteffect.handler.PlayerHandler.onEntityTick(PlayerHandler.java:34) ~[seteffect:1.16.5-1.0.6]
	at net.minecraftforge.eventbus.ASMEventHandler_2761_PlayerHandler_onEntityTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]

**Comment by Witixin1512** [comment]
I can reload just fine, what version are you using?
(Using 1.0.6)

**Comment by Neko2n** [comment]
I’m using 1.0.6, and yeah I don’t know how to reproduce this. I can reload just fine, but one of the times I reloaded led to a crash. I’m assuming I ran the command at a bad time or something, either that or its related to my config. The change I made that led to the crash though was just changing a particle’s minX and maxX from -1.0,1.0 to -2.0,2.0. I don’t exactly think that would crash, especially when the other values worked just fine.

**Comment by Witixin1512** [comment]
Post your full script, latest.log and crafttweaker.log please

**Comment by Neko2n** [comment]
[latest.log](https://github.com/Witixin1512/ArmorSetEffects/files/7573213/latest.log)
[setbonuses - Copy.txt](https://github.com/Witixin1512/ArmorSetEffects/files/7573216/setbonuses.-.Copy.txt)
[crafttweaker.log](https://github.com/Witixin1512/ArmorSetEffects/files/7573217/crafttweaker.log)

**Comment by Witixin1512** [comment]
Please send them as pastebin or gist links, I'd rather not download files
Thanks

**Comment by Neko2n** [comment]
https://pastebin.com/0Y9UBnWP - setbonuses.zs (crafttweaker script)
https://gist.github.com/NovaN4/2b00e1f5ca65b2ee67384e17d23a3091 - crafttweaker.log
https://gist.github.com/NovaN4/1de0b395ddec1111c83d8e0dddb66e24 - latest.log

**Comment by Witixin1512** [comment]
I believe this is just the modpack and your computer not reloading properly, I cannot replicate this.
Let me know if it happens again, because I cannot see what would cause this.
